# ------------------------------------------------------------------------------------------------------------------------
# Pipeline deploying a bicep file using multiple service connections
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEMO
      - DEV
      - QA
      - PROD
    default: DEMO

# ----------------------------------------------------------------------------------------------------
variables:
  - template: vars/var-common.yml

# ----------------------------------------------------------------------------------------------------
stages:
- template: templates/deploy-bicep-template.yml
  parameters:
    environmentName: ${{ parameters.deployToEnvironment }}
    bicepPath: 'infra/bicep'
    bicepFile: 'loganalytics.bicep'
    parameterFile: 'loganalytics.bicepparam'
